Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash 
 
 
-#      ▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
-#      ▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
-#      ▇▇          ▇ @Hskh56   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
-#      ▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @Hskh56
-#      ▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @Hskh56  ▇▄                 ▇▇                 ▇▇
-#      ▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source MAX BY @Hskh56
+#    ▇                                 ▇▇▇                   ▇▇▇                     ▇                   ▇▇                                 
+#    ▇                              ▇         ▇               ▇       ▆                  ▇                ▆       ▆ 
+#    ▇                           ▇               ▆             ▇          ▆              ▆             ▅            ▅
+#    ▇                        ▆ ▄▄▄ ▄▄▄  ▇           ▇              ▆          ▇          ▆ ▄▄▄ ▄▄▄ ▇               
+#    ▇                     ▇                          ▇        ▇                 ▆       ▅         ▆                       ▆
+#    ▇▇   ▇▇   ▄   ▆                               ▇    ▇                    ▆▇▇     ▇▇                          ▇▇
 #---------------------------------------------------------------------
 cd $(cd $(dirname $0); pwd)
  
@@ -22,16 +22,16 @@ Version=`lsb_release -rs | cut -f1 -d"."`
 
 if [ "$Version" == "18" ];then
 echo -e "${GREEN}
-▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
-▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
-▇▇          ▇ @Hskh56   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
-▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @Hskh56
-▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @Hskh56  ▇▄                 ▇▇                 ▇▇
-▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source MAX BY @Hskh56
+▇                                 ▇▇▇                   ▇▇▇                     ▇                   ▇▇                                 
+▇                              ▇         ▇               ▇       ▆                  ▇                ▆       ▆ 
+▇                           ▇               ▆             ▇          ▆              ▆             ▅            ▅
+▇                        ▆ ▄▄▄ ▄▄▄  ▇           ▇              ▆          ▇          ▆ ▄▄▄ ▄▄▄ ▇               
+▇                     ▇                          ▇        ▇                 ▆       ▅         ▆                       ▆
+▇▇   ▇▇   ▄   ▆                               ▇    ▇                    ▆▇▇     ▇▇                          ▇▇
 ----------------------------------------------------------------------${CNIL}"
 echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
 ${CNIL}";
-echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source MAX 
+echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source LANA 
 ${CNIL}";
 exit;
 fi
@@ -41,7 +41,7 @@ if [ ! -f "./TG" ]; then
 echo -e "${RED}
 ¦
 ¦ CAUTION:${WHITB} Your Not Dwonload TG .
-¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source MAX${CNIL} . \n
+¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source LANA${CNIL} . \n
 \n\n"
 chmod +x ./ins
 ./ins
@@ -70,10 +70,10 @@ sudo rm -fr ../.telegram-cli
 done
 else
 
-if ! screen -list | grep -q "max"; then
-screen -S max ./run R
+if ! screen -list | grep -q "lana"; then
+screen -S lana ./run R
 fi
-screen -S max -X kill
-screen -S max ./run R
+screen -S lana -X kill
+screen -S lana ./run R
 fi
 
